### ISSUE TITLE
1-01-01 deprecate inapplicable and unknown

### ISSUE THREAD

**Issue by fstuerzl** [wmo-im/wmds#196] opened 2020-10-21 09:16 UTC
**Branch**

https://github.com/wmo-im/wmds/tree/Issue196

**Summary and Purpose**  
Deprecate elements that make no sense from code table for observed variables.

**Proposal**  
Deprecate entries "inapplicable" and "unknown" from code table 1-01-01.csv.

**Reason**  
The elements "inapplicable" and "unknown" refering to the observed variable do not make sense in this context as there would be no observation to be described if the variable cannot be defined. While a nilReason makes a lot of sense in many code lists, this one is so fundamental that additional entries in the code table are required in case the existing elements are insufficient. Specifying a nilReason does not generate any meaningful information here.

**Comment by amilan17** [comment] 2020-11-13 09:48
Decision dependent on #199.

**Comment by joergklausen** [comment] 2020-12-17 14:13
@fstuerzl Create branch, expand on the reason

**Comment by fstuerzl** [comment] 2020-12-21 07:53
Branch: https://github.com/wmo-im/wmds/blob/Issue196/tables_en/1-01-01.csv

**Comment by fstuerzl** [comment] 2020-12-21 08:03
Branch: https://github.com/wmo-im/wmds/blob/Issue196/tables_en/1-01-01.csv

**Comment by joergklausen** [comment] 2020-12-21 08:03
Unknown and Invalid marked as invalid. Confirmed that branch is correct.

**Comment by fstuerzl** [comment] 2021-01-11 13:52
@RMaerz, @tomkralidis, please review the proposal and confirm or comment.

**Comment by RMaerz** [comment] 2021-01-13 21:02
confirm !

**Closed** 2021-04-26 08:34 UTC
Labels: FT21-1-validation, has branch
